static const char admin_page_settings[] = 
    "var ssid = \"%s\";"
    "var password = \"%s\";"
    "var channel = \"%d\";";

static const char admin_page_header[] = 
    "<!DOCTYPE html>\n"
    "<html lang=\"en\">\n"
    "<head>\n"
    "    <meta charset=\"UTF-8\">\n"
    "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
    "    <title>ESP32 Configuration</title>\n"
    "    <style>\n"
    "        body {\n"
    "            font-family: Arial, sans-serif;\n"
    "            margin: 0;\n"
    "            padding: 0;\n"
    "        }\n"
    "        .tabs {\n"
    "            display: flex;\n"
    "            cursor: pointer;\n"
    "            background-color: #333;\n"
    "            color: white;\n"
    "            justify-content: space-around;\n"
    "            padding: 10px 0;\n"
    "        }\n"
    "        .tabs div {\n"
    "            flex: 1;\n"
    "            text-align: center;\n"
    "            padding: 10px;\n"
    "        }\n"
    "        .tabs div:hover {\n"
    "            background-color: #555;\n"
    "        }\n"
    "        .tabs .active {\n"
    "            background-color: #555;\n"
    "            font-weight: bold;\n"
    "        }\n"
    "        .tab-content {\n"
    "            display: none;\n"
    "            padding: 20px;\n"
    "        }\n"
    "        .tab-content.active {\n"
    "            display: block;\n"
    "        }\n"
    "        input[type=\"text\"], input[type=\"password\"], select {\n"
    "            width: 95%;\n"
    "            padding: 10px;\n"
    "            margin: 10px 0;\n"
    "            border: 1px solid #ccc;\n"
    "            border-radius: 5px;\n"
    "        }\n"
    "        button {\n"
    "            padding: 10px 20px;\n"
    "            background-color: #333;\n"
    "            color: white;\n"
    "            border: none;\n"
    "            border-radius: 5px;\n"
    "            cursor: pointer;\n"
    "        }\n"
    "        button:hover {\n"
    "            background-color: #555;\n"
    "        }\n"
    "    </style>\n"
    "</head>\n";

static const char admin_page_body[] =
    "<body>\n"
    "    <div class=\"tabs\">\n"
    "        <div id=\"tab-settings\" class=\"active\">Hotspot Settings</div>\n"
    "        <div id=\"tab-evil-twin\">EVIL TWIN</div>\n"
    "        <div id=\"tab-fakeap\">FAKEAP</div>\n"
    "    </div>\n"
    "    <div id=\"content-settings\" class=\"tab-content active\">\n"
    "        <h2>Hotspot Settings</h2>\n"
    "        <form id=\"hotspot-form\" action=\"/save_ap\" method=\"post\">\n"
    "            <label for=\"ssid\">SSID:</label><br>\n"
    "            <input type=\"text\" id=\"ssid\" name=\"ssid\" placeholder=\"Enter SSID\" required><br>\n"
    "            <label for=\"password\">Password:</label><br>\n"
    "            <input type=\"text\" id=\"password\" name=\"password\" placeholder=\"Enter Password\"><br>\n"
    "            <label for=\"channel\">Channel:</label><br>\n"
    "            <input type=\"text\" id=\"channel\" name=\"channel\" placeholder=\"Enter Channel (1-13)\" required><br>\n"
    "            <button type=\"submit\">Save Settings</button>\n"
    "        </form>\n"
    "    </div>\n"
    "    <div id=\"content-evil-twin\" class=\"tab-content\">\n"
    "        <h2>EVIL TWIN</h2>\n"
    "        <p>Configure and monitor the Evil Twin attack settings here.</p>\n"
    "    </div>\n"
    "    <div id=\"content-fakeap\" class=\"tab-content\">\n"
    "        <h2>FAKEAP</h2>\n"
    "        <p>Configure and monitor the Fake Access Point settings here.</p>\n"
    "    </div>\n"
    "    <script>\n"
    "        const tabs = document.querySelectorAll('.tabs div');\n"
    "        const contents = document.querySelectorAll('.tab-content');\n"
    "        tabs.forEach(tab => {\n"
    "            tab.addEventListener('click', () => {\n"
    "                tabs.forEach(t => t.classList.remove('active'));\n"
    "                contents.forEach(c => c.classList.remove('active'));\n"
    "                tab.classList.add('active');\n"
    "                const contentId = `content-${tab.id.split('-')[1]}`;\n"
    "                document.getElementById(contentId).classList.add('active');\n"
    "            });\n"
    "        });\n"
    "        document.getElementById('ssid').value = ssid;\n"
    "        document.getElementById('password').value = password;\n"
    "        document.getElementById('channel').value = channel;\n"
    "    </script>\n"
    "</body>\n"
    "</html>\n";